apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanaones
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mynginx
  template:
    metadata:
      labels:
        run: mynginx
    spec:
      containers:
      - image: nginx
        name: nanaones
        ports:
        - containerPort: 80
